version: '3.8'

services:
  backend-services:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: todo_db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
