apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  selector:
    app: frontend 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3001
  type: ClusterIP